from matplotlib import pyplot as plt
from src.game_env import GameEnv


def main():
    env = GameEnv()
    img, _ = env.reset(42)
    print(img.shape)
    plt.figure()
    plt.imshow(img)
    plt.show()

    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    env.step('up')
    obs, _, _, _, _ = env.step('right')

    plt.figure()
    plt.imshow(obs)
    plt.show()

    res_obs, _ = env.reset(42)
    plt.figure()
    plt.imshow(res_obs)
    plt.show()

    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')
    env.step('left')

    obs2, _, _, _, _ = env.step('right')

    plt.figure()
    plt.imshow(obs2)
    plt.show()


if __name__ == "__main__":
    main()
